### ISSUE TITLE
[KB] Add GitHub token permissions for dwenegar/upload-release-assets Action

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/secure-workflows#10]

**Comment by Devils-Knight** [comment]
### Analysis
```yml
Action Name: dwenegar/upload-release-assets
Action Type: Node
GITHUB_TOKEN Matches: GITHUB_TOKEN
Top language: JavaScript
Stars: 6
Private: false
Forks: 4
```
### Endpoints Found
|Endpoint | Permission|
|---------| ----------|
repos.get | read
repos.getRelease | read
repos.uploadReleaseAsset | write

#### FollowUp Links.
https://github.com/dwenegar/upload-release-assets/blob/fc5bc557b51cf4fc168f11bebc1e20a17949f0d2/lib/upload-release-assets.js
https://github.com/dwenegar/upload-release-assets/blob/fc5bc557b51cf4fc168f11bebc1e20a17949f0d2/dist/index.js

### action-security.yml
```yaml
name: 'Upload Multiple Assets to a Release'
github-token:
  environment-variable-name: <FigureOutYourself>
  permissions:
    contents: write
```
