### ISSUE TITLE
[KB] Add GitHub token permissions for vmactions/netbsd-vm Action

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/secure-workflows#6]

**Comment by Devils-Knight** [comment]
### Analysis
```yml
Action Name: vmactions/netbsd-vm
Action Type: Node
GITHUB_TOKEN Matches: TOKEN
Top language: JavaScript
Stars: 0
Private: false
Forks: 0
```
### action-security.yml
