### ISSUE TITLE
[KB] Add GitHub token permissions for step-security/wait-for-secrets Action

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/secure-workflows#9]

**Comment by Devils-Knight** [comment]
### Analysis
```yml
Action Name: step-security/wait-for-secrets
Action Type: Node
GITHUB_TOKEN Matches: token,Token,TOKEN
Top language: TypeScript
Stars: 1
Private: false
Forks: 1
```
### Endpoints Found
|Endpoint | Permission|
|---------| ----------|

#### FollowUp Links.
https://github.com/step-security/wait-for-secrets/blob/1037fa13dc44ea7eed7ef12e44fd73e46d164a38/src/index.ts

### action-security.yml
```yaml
name: "Get MFA Secrets"
github-token:
  environment-variable-name: <FigureOutYourself>
    is-default: false
  permissions:
```
